### ISSUE TITLE
It doesn't log me in

### ISSUE THREAD

**Issue by Juancafr** [s0t7x/decky-sunshine#54]
I've installed it manually on the Deck, both from desktop mode to create a username and passworld, and by manually entering the folder into Decky. When I try to log in, it never does. I enter my details and click login, and it returns me to the previous Decky screen. Any ideas?

**Comment by causa-prima** [comment]
If you are talking about [nightly-20250326-073454](https://github.com/s0t7x/decky-sunshine/releases/tag/nightly-20250326-073454) : my apologies, that might be my fault. I assumed that before my pull request #51 was merged, someone would actually test it. I did not, as at the point of writing it, I did not look into how to do that. I fixed the bugs I introduced as well as some other bugs in #55, so please check again after this has been merged a new (nightly) version is available.

**Comment by Juancafr** [comment]
> I'm a bit confused about what exactly you installed and how installed it. Normally, the Decky Sunshine plugin would be installable from the Decky Loader store, but it is currently not listed (see [#47](https://github.com/s0t7x/decky-sunshine/issues/47) for more about the status on that). Thus, currently the easiest way to install Decky Sunshine is enabling "Developer mode" in the "General" section of the Decky Loader settings, and then go to the "Developer" section of the Decky Loader settings and enter the URL of a zip of a release (e.g. the [latest nightly](https://github.com/s0t7x/decky-sunshine/releases/tag/nightly-20250402-064303)) the into the "Install Plugin from URL" box and hit "Install". This will install Decky Sunshine, which will take care of installing Sunshine on the first start. I recommend deleting the thing you installed manually before doing so to have a clean state to start from, which would make it easier to help you with problems with Decky Sunshine later.
> 
> Edit: I forgot to mention that you could use a URL shortener like tinyurl to make it easier to enter the URL of the release, I did just that for you, so just enter https://tinyurl.com/5cjttamu into that box, which is a link to the zip from [nightly-20250402-064303](https://github.com/s0t7x/decky-sunshine/releases/tag/nightly-20250402-064303)

Yes, I know that, I installed Decky's nightly through developer mode and then I put in the two files you modified

**Comment by ZynxGit** [comment]
I'm not able to login from game mode. I've tried resetting credentials but no success. Logs don't show anything about incorrect credentials. On top of that, I've tried logging into the web UI from Chrome through game view and no dice also. I'm able to reach the web UI from desktop mode and stream from there, but that's obviously not practical. 

The logs do state that Sunshine is running and that Decky Sunshine isn't authorized, but I'm convinced that somehow Sunshine isn't running properly since Chrome wasn't working either.

**Comment by causa-prima** [comment]
Please share your logs of Decks Sunshine.

Also, in your last answer you stated that you got it working. Did you mean you got it working from game mode? If so, did you change anything in between? Does it work again if you recreate your credentials again? 

Note: to check whether Sunshine is running, Decky Sunshine checks if there is a process with the exact name `sunshine'. If you have SSH access to your Steam Deck, please connect to it via SSH when the plugin shows Sunshine is running, execute the command `ps -aux | grep sunshine | grep -v grep` and show us the results of that command. The expected result would be three lines - two from `bwrap` and one from the actual `sunshine` process. Also, please execute `pgrep -x sunshine` and report the results. The expected result would be a single number (the process id of the `sunshine` process), the same number as returned in the previous command).

To check whether you are authorized (i.e. the credential you entered are valid), a request to `https://127.0.0.1/api/apps` is made an the results are checked. If you are using the latest nightly, the logs should show if anything went wrong with that request. If there is nothing more than a statement that you are not authorized, there is probably a problem with your credentials, i.e. they are either wrong, or Decky Sunshine has some bug when creating that request. If you have SSH access to your deck, you could check your credentials with the following command: `curl -u user:pass -X GET -k https://localhost:47990/api/apps` (don't forget to replace `user` and `pass` with your actual credentials).

**Comment by Avokkrii** [comment]
Hijacking this thread as it seems to be the only active one regarding this nightly build.

I've installed it from scratch through the provided URL, and the plugin installed just fine.

After opening it, I enabled sunshine and it gave me no error or further instructions, just asked for the pairing pin.

However, on my device (a tablet) running moonlight, I cannot find the host (the Deck, with Decky Sunshine enabled) to begin pairing.

They're both on the same network.

Anything I've missed to get it working? Any additional step that isn't in the readme?

Thanks in advance.

@causa-prima

**Comment by causa-prima** [comment]
@Avokkrii You could just have opened your own thread as well, they are free ;-)

About Moonlight not finding Sunshine on your Steam Deck: I don't know. I tried two different Moonlight instances when testing the latest nightly, one on my Nvidia Shield and a portable version on my Windows laptop. On both, I waited for maybe half a minute without them finding Sunshine running on the Deck, even though being on the same network. I got impatient and just entered the IP of the Deck manually, which worked just fine.

From your comment it seems like you got it working on some machine, but it is not working on another one (your tablet). Is that correct? If so, this would indicate that there is nothing fundamentally wrong with the Sunshine/Decky Sunshine side, but probably with the other factors (network configuration, Moonlight, the tablet..). Other than that, I'm out of ideas.

**Comment by Avokkrii** [comment]
No, I failed to get it working on any machine. The plugin seems to indicate the server is up and running, but I can't seem to find it on any Moonlight clients.

Just tried directly inputting the Deck's IP address, and that seemed to work fine. Unsure what the problem causing the (Moonlight) clients not to discover the (Sunshine) server is, but direct connection works.

Thanks a lot!

**Comment by SpicyMelonCrab** [comment]
Hello Causa-Prima.

I wanted to let you know that I tried the latest nightly and actually, it did work! I am logged into my desktop right now!

It appears that you've mostly got it fixed. I know those other two fellows are still having trouble but it works for me! (or at least it did this time.)

**Comment by causa-prima** [comment]
@Avokkrii: I am assuming you did not install and setup Sunlight separately, i.e. you only installed decky-sunshine, right? If so, then the default username and password is "decky_sunshine". Can you log in with these credentials? If not, you could try resetting the username and password using `sunshine -creds <new username> <new password>` (taken from [the Sunshine documentation](https://docs.lizardbyte.dev/projects/sunshine/v0.14.0/troubleshooting/general.html)). Hope any of this solves your problem.

**Comment by causa-prima** [comment]
@Avokkrii: Please check whether this is still an issue with the latest version (0.5.0). If it is, please provide the logs.

**Comment by Avokkrii** [comment]
> [@causa-prima](https://github.com/causa-prima) This does still seem to be an issue. Fresh install of the Sunshine flatpak. Set credentials and logged in via Sunshine desktop web UI. Installed decky-sunshine via Decky Store. Refuses to login in gaming mode or Big Picture desktop mode and just throws me back to the previous "You need to log into Sunshine" and Login button dialog.

I've also gotten it after uninstalling the preview build and installing it from the Store. But using `decky_sunshine` as the username and password logs me in just fine in gaming mode, and everything works from there.

You should try uninstalling the Sunshine flatpak and the plugin, and then installing *only* the plugin and letting it automatically install and configure Sunshine for you; after that, the default credentials should work. I also tried setting it up manually previously, but my credentials never worked, I'm not sure if the plugin replaces them or something, but in any case the default ones do work.



> [@Avokkrii](https://github.com/Avokkrii): Please check whether this is still an issue with the latest version (0.5.0). If it is, please provide the logs.

Sorry for not answering this earlier! We ended up discussing this in another issue (#58) two weeks ago, and it's been working since then when using the default credentials.

**Comment by causa-prima** [comment]
@Bonhovis: What you are describing seems to be just what was reported in #23. Please refer to my [latest comment there](https://github.com/s0t7x/decky-sunshine/issues/23#issuecomment-2952736577). It would be great if you could report back in that issue whether my assumptions are correct.

Closing this issue as it is solved for all the original participants.

**Comment by jeeff6** [comment]
>which is what should happen if you add the `sudo` in front of the command? If so, is there any unusual output of that command? Can you also not login with these credentials on the web GUI of Sunshine after executing the command?

With `sudo` at the beginning of command, i get error ("flatpak run" is not intended to be run as 'sudo flatpak run'. Use 'sudo -i' or 'sudo -l' instead and invoke "flatpak run" from inside the new shell.). I ran sudo -i and it opened a new shell line, I typed in the flatpak command in the shell but after that, going back to game mode it still doesn't log me in with the cred I made. Adding `sudo` in that command in the shell also get the same error. Trying to log in on web UI in desktop mode with the cred I made after running the command and of course, prompt back to log in form widget.

**Comment by causa-prima** [comment]
Glad to read you found a solution 🥳 I hope this is a stable solution 🤞 

From your steps I also do not understand which thing that you did made a difference, but at least now I know that `sudo` doesn't work as I expected. I'll have to try these steps myself at some point to be able to create a step-by-step guide. 

Thanks for your feedback! ❤️
